#!/usr/bin/php
<?php
/**
 * modeller
 */
namespace CoreORM;

if (is_file(__DIR__ . '/vendor/autoload.php')) {
    // when it's in framework dir
    require_once __DIR__ . '/vendor/autoload.php';
}
if (is_file(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}
use CoreORM\Utility\ModelGenerator;
// run model gen
ModelGenerator::main($argv);
?>
